version: '2'
services:
  spark:
    build: ./container/spark
    ports:
      - "8088:8088"
      - "8042:8042"
      - "4040:4040"
    depends_on:
      - elasticsearch
      - kibana
  elasticsearch:
    build: ./container/elasticsearch
    ports:
      - "9200:9200"
  kibana:
    image: kibana:4.5
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"