version: '2'
services:
  spark:
    build: ./container/spark
    ports:
      - "8088:8088"
      - "8042:8042"
      - "4040:4040"

# docker run -it -p 8088:8088 -p 8042:8042 -p 4040:4040 -h sandbox sequenceiq/spark:1.6.0 bash